# -*- coding: utf-8 -*-
"""Movie Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXQdg_Pe-tONNs-5zL4C7x8FTez_IStm
"""

! pip install pandas
! pip install numpy
! pip install scikit-learn
! pip install matplotlib
! pip install seaborn

import pandas as pd
import numpy as np
import ast
from sklearn.preprocessing import MultiLabelBinarizer, MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

import pandas as pd
# Load the movie metadata CSV file, specifying the encoding
df = pd.read_csv("/content/imdb_top_1000.csv", low_memory=False, encoding='latin-1')

df.describe()

#checking all the columns from datasets
df.columns

#we only need series title, genres, IMDB rating, meta score, no.of votes etc
movies = df[[ 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating',  'Meta_score', 'Director',
       'Star1',  'No_of_Votes', 'Gross']].copy()
print(movies)

# Drop rows with missing values in important columns
movies = movies.dropna(subset=[   'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
        'No_of_Votes', 'Gross']).copy()

#Extract genre names from JSON-like string

def parse_genre(genre_str):
    if pd.isna(genre_str):
        return []
    return [g.strip() for g in genre_str.split(',')]

#Apply the parsing function to each row

movies['genre_list'] = movies['Genre'].apply(parse_genre)

print (movies['genre_list'])

# 1. Feature Selection and Engineering:
# Assuming you want to use 'IMDB_Rating' and 'Meta_score' as features:
features = movies[['IMDB_Rating', 'Meta_score']]

# Handle missing values (if any) - replace with 0 for now
features = features.fillna(0)

# 2. Assign to `final_features`:
final_features = features  # or final_features = features.values
# if your KMeans implementation requires a NumPy array


inertia_values = []
silhouette_scores = []
k_values = range(2, 21)

for k in k_values:
    kmeans_model = KMeans(n_clusters=k, random_state=42)
    kmeans_model.fit(final_features)
    inertia_values.append(kmeans_model.inertia_)
    silhouette_scores.append(silhouette_score(final_features, kmeans_model.labels_))

# Plotting
fig, axs = plt.subplots(1, 2, figsize=(14, 5))

axs[0].plot(k_values, inertia_values, marker='o')
axs[0].set_title('Elbow Method for Optimal k')
axs[0].set_xlabel('Number of clusters (k)')
axs[0].set_ylabel('Inertia')
axs[0].grid(True)

axs[1].plot(k_values, silhouette_scores, marker='s', color='green')
axs[1].set_title('Silhouette Scores for Different k')
axs[1].set_xlabel('Number of clusters (k)')
axs[1].set_ylabel('Silhouette Score')
axs[1].grid(True)

plt.tight_layout()
plt.show()

# Genre Bar Plot
genre_counts = movies['genre_list'].explode().value_counts().sort_values(ascending=False)
#print(genre_counts)
plt.figure(figsize=(12, 6))
sns.barplot(x=genre_counts.index, y=genre_counts.values, palette='viridis')
plt.title('Genre Distribution')
plt.xticks(rotation=45)
plt.ylabel('Number of Movies')
plt.xlabel('Genre')
plt.tight_layout()
plt.show()

# This turns genre lists into binary features
mlb = MultiLabelBinarizer()
genre_encoded = mlb.fit_transform(movies['genre_list'])
genre_df = pd.DataFrame(genre_encoded, columns=mlb.classes_)
print(genre_df)

# We scale IMDB_Rating and Meta_score to range [0, 1]
scaler = MinMaxScaler()
# Changed 'vote_average' and 'popularity' to 'IMDB_Rating' and 'Meta_score' respectively
scaled_features = scaler.fit_transform(movies[['IMDB_Rating', 'Meta_score','No_of_Votes']])
scaled_df = pd.DataFrame(scaled_features, columns=['IMDB_Rating', 'Meta_score','No_of_Votes'])
print(scaled_df)

#Combine all features into one matrix
final_features = pd.concat([genre_df, scaled_df], axis=1)
#print(final_features)

pca = PCA(n_components=2)
reduced_features = pca.fit_transform(final_features)

plt.figure(figsize=(8,6))
sns.scatterplot(x=reduced_features[:, 0], y=reduced_features[:, 1], color='blue')
plt.title('unclustered Movie Data (2D PCA)')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.show()

from sklearn.cluster import KMeans
pca = PCA(n_components=2)
reduced_features = pca.fit_transform(final_features)

kmeans_model = KMeans(n_clusters=4, random_state=42)
clusters = kmeans_model.fit_predict(final_features)

plt.figure(figsize=(8, 6))
sns.scatterplot(x=reduced_features[:, 0], y=reduced_features[:, 1], hue=clusters, palette='viridis')

plt.title('Movie clusters')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA component 2')

plt.tight_layout()
plt.show()

#step 2: fit kmeans and assign clusters
optimal_K = 7
kmeans = KMeans(n_clusters=optimal_K, random_state=42)
movies['cluster'] = kmeans.fit_predict(final_features)
#step3: plot scatter with cluster color
plt.figure(figsize=(12,6))
sns.scatterplot(
    x=reduced_features[:, 0],
    y=reduced_features[:, 1],
    hue=movies['cluster'],
    palette='tab10',
    s=60,

    alpha=0.7
)
plt.title('Movie clusters of movies(2D PCA)')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend(title='Cluster', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

optimal_K = 7
kmeans = KMeans(n_clusters=optimal_K, random_state=42)
movies['cluster'] = kmeans.fit_predict(final_features)


# Plot how many movies per cluster
plt.figure(figsize=(10, 5))
sns.countplot(x=movies['cluster'], palette='coolwarm')
plt.title('Number of Movies per Cluster')
plt.xlabel('Cluster')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

#Define recommendation function
def recommend_movies(movie_title, movies, n=5): # Pass 'movies' as an argument
    """
    Recommend similar movies based on genre, popularity, and rating using clustering.

    Parameters:
        movie_title (str): Title of the movie to base recommendations on.
        movies (pd.DataFrame): The DataFrame containing movie data. # Add movies to docstring
        n (int): Number of similar movies to return.

    Returns:
        pd.DataFrame: Top N recommended movies in the same cluster.
    """
    # Lowercase comparison for robust matching
    target = movies[movies['Series_Title'].str.lower() == movie_title.lower()] # Changed 'title' to 'Series_Title'

    if target.empty:
        return f" Movie titled '{movie_title}' not found in dataset."

    # Get the cluster of the target movie
    cluster_id = target['cluster'].values[0]

    # Get all movies from the same cluster
    similar_movies = movies[(movies['cluster'] == cluster_id) &
                            (movies['Series_Title'].str.lower() != movie_title.lower())] # Changed 'title' to 'Series_Title'

    # Return top N based on vote_average and popularity
    # Assuming you have these columns
    # If not, replace with the actual columns you want to use
    return similar_movies[['Series_Title', 'IMDB_Rating', 'No_of_Votes']].sort_values( # Changed column names
        by=['IMDB_Rating', 'No_of_Votes'], ascending=False).head(n) # Changed column names




# Example usage:
print(" Recommended movies similar to 'The Godfather':")
print(recommend_movies("The Dark Knight", movies, n=5)) # Pass 'movies' when calling the function

pip install streamlit

!pip install streamlit pyngrok --quiet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # Dummy recommend_movies function (replace with your real one)
# def recommend_movies(movie_name, n=5):
#     return ["The Godfather",
#         "The Dark Knight",
#  "The Godfather: Part II ",
#            "12 Angry Men  ",
#           "Pulp Fiction " ]
# 
# st.title("🎬 Movie Recommender System")
# movie_name = st.text_input("Toy story:")
# if st.button("Recommend"):
#     recommendations = recommend_movies(movie_name, n=5)
#     st.write("Recommended Movies:")
#     for movie in recommendations:
#         st.write(f"- {movie}")
#

from pyngrok import ngrok

# Set your ngrok auth token
ngrok.set_auth_token("2tzHJs80GIMPdQm78EkGwtRXaz5_6YLjwPAaifTvg99wEbkvA")

from pyngrok import ngrok

# Kill any running tunnels
ngrok.kill()

# Create a tunnel to the streamlit port 8501
# Specify 'addr' instead of 'port'
public_url = ngrok.connect(addr=8501)
print(f"Public URL: {public_url}")

# Run streamlit app
!streamlit run app.py &> /dev/null &